[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = ["cauesmelo <cauesmelo@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "0.109.0"
uvicorn = "0.26.0"
pydantic-settings = "2.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
